# Generated by Django 5.0.6 on 2024-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_adress',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excertp',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='No excerpt provided.', max_length=200),
        ),
    ]
