# Generated by Django 5.0.6 on 2024-06-06 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='email_address',
            field=models.EmailField(help_text="Enter the author's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Enter the first name of the author', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Enter the last name of the author', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='Select the post to comment on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Enter the comment text', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(help_text='Enter the email address of the user', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(help_text='Enter the name of the user', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Select the author of the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter the content of the post', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True, help_text='The date when the post was created or updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(help_text='Enter a short excerpt of the post', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Upload an image for the post', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Enter a unique slug for the post', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Select tags for the post', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter the title of the post', max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(help_text='Enter a tag caption', max_length=20),
        ),
    ]
